---
title: "Managing Felis catus impact on a protected island: Outcomes of an ongoing socio-ecological strategy in the Martín García Island Reserve (Buenos Aires, Argentina)"
author: "Ian Barbe, Lucía Inés Rodríguez-Planes, María del Rosario Jacoby, Andrea Szmelc, Gloria Domínguez, Nazareno Asín, María Eugenia Cueto, María Marcela Orozco"
email: iannbarbe@gmail.com
year: 2025
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GitHub Documents

This is an R Markdown format used for publishing markdown documents to GitHub. When you click the **Knit** button all R code chunks are run and a markdown file (.md) suitable for publishing to GitHub is generated.

## Including Code

```{r library}
library(tidyverse)
library(readxl)
library(lme4)
library(ggeffects)
library(performance)
library(emmeans) 
library(writexl)
library(magrittr) 
library(MuMIn) 
library(glmmTMB) 
library(MASS) 
library(pscl)
library(gridExtra)
```

```{r GLMM Sighted cats}

#Medium zone
cats <- read_excel("R data/Fig3a,b.SightedCats18-21_GLMM.xlsx") %>%
  rename(abundance = 1) %>%
  mutate(year = factor(year)) %>%
  mutate (index = abundance/effort)%>%
  filter(zone == "Medium")

#Low zone ---
cats_exp <- read_excel("R data/Fig3a,b.SightedCats18-21_GLMM.xlsx") %>%
  rename(abundance = 1) %>%
  mutate(year = factor(year)) %>%
  mutate (index = abundance/effort)%>%
  filter(zone != "High") %>% 
  filter(zone == "Low")

#year as character
cats_exp$year <- as.character(cats_exp$year)
class(cats_exp$year)
cats_exp$abundance

#### GLMM medium zone model for sigthed cats----

mod_cats <- glmer(abundance ~ year + (1|transect) + offset(log(effort)),
                   family = "poisson", data = cats)

check_overdispersion(mod_cats)
check_model(mod_cats)
summary(mod_cats)

## Likelihood Ratio Test
mod_cats %>% 
  update(.~.-year) %>% 
  anova(mod_cats, test = "Chisq") #AIC

#predicted values
cats$predicted <- predict(mod_cats, type= "response") 
cats$pred_index <- cats$predicted/cats$effort

#predicted per year
year_predicted <- predict(mod_cats, type="response")
year_predicted

#random predicted values with CI 
cats_predict_random <- ggpredict(mod_cats, terms = "year", type = "random")
cats_predict_random
```
```{r Tukey}
mod_cats %>% 
  emmeans(list(pairwise~year), type="response"   )
  
# CI
  emms_cats <- emmeans(mod_cats, "year", type="response")  
  summary(emms_cats)
  confint(pairs(emms_cats))
```

### L. wiegmannii lizard -----
```{r lizard GLM}
l.w_lizard <- read_excel("R data/Fig4a.Lw_lizard18-21_GLM.xlsx") %>%
  rename(abundance = 1) %>%
  mutate(year = factor(year)) %>%
  mutate(index = abundance/effort)

#model
mod_lizard1 <- glm(abundance ~ year +  offset(log(effort)),
               family = "poisson", data = l.w_lizard)


check_overdispersion(mod_lizard1)
check_model(mod_lizard1)

#'[Binomial negativa'] 
mod_lizard2 <- glmmTMB(abundance ~ year,data=l.w_lizard,
                          family="nbinom2") 

check_overdispersion(mod_lizard2)
check_model(mod_lizard2)

#AIC
AIC(mod_lizard1,mod_lizard2)

summary(mod_lizard2)
l.w_lizard$predicted <- predict(mod_lizard2, type= "response") 
lizard_predindex <- l.w_lizard$predicted/l.w_lizard$effort

lizard_predict <- ggpredict(mod_lizard2, terms = "year", type = "fixed")
lizard_predict

```
```{r Tukey}
## emmeans
mod_lizard2 %>% 
  emmeans(list(pairwise~year), type = "response")

#CI
emms_lizard <- emmeans(mod_lizard2, "year", type="response")
summary(emms_lizard)
confint(pairs(emms_lizard))
```

### Caprimulgus spp.-----
```{r nightjars GLM}
nightjars <- read_excel("R data/Fig4b.Nightjars18-21_GLM.xlsx") %>% 
  rename(abundance = 1) %>%
  mutate(year = factor(year))

#model
mod_ng <- glm(abundance ~ year +  offset(log(effort)),
                      family = "poisson", data = nightjars)
check_overdispersion(mod_ng)
check_model(mod_ng)

summary(mod_ng)

nightjars$predicted <- predict(mod_ng, type= "response") 
nightjars_predindex <- nightjars$predicted/nightjars$effort

# predicted values
nightjars_predict <- ggpredict(mod_ng, terms = "year", type = "fixed")
nightjars_predict

```
```{r Tukey}
## emmeans
mod_ng %>% 
  emmeans(list(pairwise~year), type = "response")
#CI
emms_ng <- emmeans(mod_ng, "year", type="response")
summary(emms_ng) 
confint(pairs(emms_ng))
```

```{r GLMM Tegu lizard}
tegu <- read_excel("R data/Fig5.Tegu18-21_GLMM.xlsx")%>%
  rename(abundance = 1) %>%
  mutate(year = factor(year))

##GLMM model

m_sat <- glmer(abundance ~ year*zone + (1|transect) + offset(log(effort)),
                      family = "poisson",
                      data = tegu)
check_overdispersion(m_sat)
summary(m_sat)

## Likelihood Ratio Test

m_sat %>% 
  update(.~. -year:zone) %>% 
  anova(m_sat, test = "Chisq") # removing the interaction does not significantly reduce the deviance value.It is discarded 
m_sat %>% 
  update(.~. -year:zone - zone) %>% # The zone influences the deviance.
  anova(m_sat, test = "Chisq")
m_sat %>% 
  update(.~. -year:zone - year) %>% # The year influences the deviance.
  anova(m_sat, test = "Chisq")

#best model
mod_tegu <- glmer(abundance ~ year + zone + (1|transect) + offset(log(effort)),
                      family = "poisson", data = tegu)

check_overdispersion(mod_tegu)
check_model(mod_tegu)
summary(mod_tegu)


## predicted values + CI
tegu$predicted <- predict(mod_tegu, type= "response") 
tegu$pred_index <- tegu$predicted/tegu$effort
tegu_predict <- ggpredict(mod_tegu,terms = c("year","zone"))

```
```{r Tukey}
## emmeans YEAR
mod_tegu %>% 
  emmeans(list(pairwise~year),
          type = "response")
#CI year
  emms_tegu_year <- emmeans(mod_tegu, "year", type="response")  
  summary(emms_tegu_year)
  confint(pairs(emms_tegu_year))
  
#emmeans ZONE
mod_tegu %>% 
  emmeans(list(pairwise~zone),
          type = "response")
#CI zone
  emms_tegu_zone <- emmeans(mod_tegu, "zone", type="response") 
  summary(emms_tegu_zone) 
  confint(pairs(emms_tegu_zone))
  
  
```
############### Interviews --------------------------
```{r Table5 interviews project need to continue}
#Table 5. Need to continue the project data ----------------

#Frequency of affirmative responses related to project continuation on MGI
#Table5 matrix (data from Table5_data.xlsx)
Table5 <- matrix(c(24, 2, 50, 1), nrow = 2, byrow = TRUE)
#chi-square test
projectchisq <- prop.test(Table5)
print(projectchisq)
```
```{r Fig6. cat abundance perceptons interviews}
#Fig.6. Community perceptions of cat abundance at the beginning of the project, by category (Surrounding houses and Island) and year (2019-2021)-------------

#island (data from Fig6. Island data.xlsx) -------------------------------
#2019 
island_2019 <- matrix(c(11, 3, 14), nrow = 1, byrow = TRUE)
colnames(island_2019) <- c("lower", "higher", "total")
# lower vs. higher
result_chi_cuad_island_2019 <- chisq.test(island_2019)
result_chi_cuad_island_2019$expected
print(result_chi_cuad_island_2019)

#island 2021
island_2021 <- matrix(c(20, 7, 27), nrow = 1, byrow = TRUE)
colnames(island_2021) <- c("lower", "higher", "total")
# lower vs. higher
result_chi_cuad_island_2021 <- chisq.test(island_2021)
result_chi_cuad_island_2021$expected
print(result_chi_cuad_island_2021)

#Surrounding houses (data from Fig6. Surrounding houses data.xlsx) ------------------
#2019
surroundings_2019 <- matrix(c(18, 2, 20), nrow = 1, byrow = TRUE)
colnames(surroundings_2019) <- c("lower", "higher", "total")
# lower vs. higher
result_chi_cuad_surroundings_2019 <- chisq.test(surroundings_2019)
print(result_chi_cuad_surroundings_2019)

#2021
surroundings_2021 <- matrix(c(26, 5, 31), nrow = 1, byrow = TRUE)
colnames(surroundings_2021) <- c("lower", "higher", "total")
# lower vs. higher
result_chi_cuad_surroundings_2021 <- chisq.test(surroundings_2021)
print(result_chi_cuad_surroundings_2021)
```